# Exercise 2: Build a PyPSA Model

**Presenter** <br>
Priyesh Gosai <br>
Energy Systems Modeller <br>
priyesh@innovateimpact.com <br>

**Course Details**<br>
Modelling Integrated Power Markets <br>
Johannesburg, South Africa <br>
20-24 April 2026 <br>

## Prepare Google Colab Environment

In [1]:
lesson_number = 2
print(f'lesson{lesson_number}')

lesson2

In [ ]:
#@title Connect to Google Drive {display-mode:"form"}
CONNECT_TO_DRIVE = False #@param {type:"boolean"}

import os

if CONNECT_TO_DRIVE:
    from google.colab import drive
    # Mount Google Drive
    drive.mount('/content/drive')

    # Define the desired working directory path
    working_dir = f'/content/drive/MyDrive/ich-modelling-2026'
    lesson_folder = f'lesson-{lesson_number}'
    lesson_dir = os.path.join(working_dir, lesson_folder)

    # Create the working directory if it doesn't exist
    if not os.path.exists(working_dir):
        os.makedirs(working_dir)
        print(f"Directory '{working_dir}' created.")
    else:
        print(f"Directory '{working_dir}' already exists.")

    # Create the lesson directory if it doesn't exist
    if not os.path.exists(lesson_dir):
        os.makedirs(lesson_dir)
        print(f"Directory '{lesson_dir}' created.")
    else:
        print(f"Directory '{lesson_dir}' already exists.")

    # Change the current working directory to the lesson directory
    os.chdir(lesson_dir)

    print(f"Current working directory: {os.getcwd()}")
else:
    print("Not connecting to Google Drive.")

In [ ]:
#@title Install Packages {display-mode:"form"}
INSTALL_PACKAGES = False #@param {type:"boolean"}

import os

# Check if packages have already been installed in this session to prevent re-installation
if INSTALL_PACKAGES and not os.environ.get('PYPSA_PACKAGES_INSTALLED'):
  !pip install git+https://github.com/pypsa/pypsa
  !pip install pypsa[excel] 
  !pip install folium mapclassify cartopy gurobipy
  os.environ['PYPSA_PACKAGES_INSTALLED'] = 'true'
elif not INSTALL_PACKAGES:
  print("Skipping package installation.")
else:
  print("PyPSA packages are already installed for this session.")

In [ ]:
#@title Download the file for this notebook {display-mode:"form"}
DOWNLOAD_FILE = False #@param {type:"boolean"}

if DOWNLOAD_FILE:
    !gdown "https://drive.google.com/uc?id=1My8j2qRcjjhVhC5bL657oYTk7-OKDxkE"

else:
    print("Skipping file download.")

#### Case Description

This cases demonstrates the method for building a PyPSA network programatically. 


##### PyPSA Features Used

- Creating a network
- Accessing the components using the API
- Viewing static data
- View dynamic data
- Run the optimiser
- Inspect results
- Plot results


##### Non-Standard PyPSA Features

This notebook will only use standard features in PyPSA. 

### Lesson Task

Access the static and dynamic data in each cell. 

* Identify the data types 
* Access specific columns and rows in the data. 
* Plot data.

In [ ]:
import pypsa
import pandas as pd
pypsa.options.api.new_components_api = True

n = pypsa.Network()

In [3]:
n.set_snapshots(pd.date_range('2025-01-01', '2025-12-31 23:00', freq='h'))

In [4]:
n.add('Carrier',['gas','AC'])

In [5]:
n.add('Bus','Location',carrier = 'AC')

In [6]:
n.add('Generator',
      'Generator A',
      bus = 'Location', 
      p_nom = 500, 
      marginal_cost = 1,
      p_nom_extendable = True
      )

In [ ]:
n.add('Generator',
      'Generator A',
      bus = 'Location', 
      p_nom = 500, 
      marginal_cost = 1,
      p_nom_extendable = False
      )

WARNING:pypsa.network.io:The following generators are already defined and will be skipped (use overwrite=True to overwrite): Generator A

In [8]:
n.add('Load',
      'Load A',
      bus = 'Location',
      p_set = 100,
      carrier = 'gas')

In [9]:
n.add('Load',
      'Load B',
      bus = 'Location',
      p_set = 100,
      carrier = 'gas')

In [10]:
n.optimize()

C:\Users\PriyeshGosai\AppData\Local\Temp\ipykernel_33848\1261279110.py:1: FutureWarning: The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.
  n.optimize()
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.22s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 8761 primals, 26281 duals
Objective: 1.75e+06
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-ext-p-lower, Generator-ext-p-upper were not assigned to the network.

('ok', 'optimal')

In [11]:
n.generators.dynamic.p

name                 Generator A
snapshot
2025-01-01 00:00:00        200.0
2025-01-01 01:00:00        200.0
2025-01-01 02:00:00        200.0
2025-01-01 03:00:00        200.0
2025-01-01 04:00:00        200.0
...                          ...
2025-12-31 19:00:00        200.0
2025-12-31 20:00:00        200.0
2025-12-31 21:00:00        200.0
2025-12-31 22:00:00        200.0
2025-12-31 23:00:00        200.0

[8760 rows x 1 columns]

In [12]:
n.loads.dynamic.p

name                 Load A  Load B
snapshot
2025-01-01 00:00:00   100.0   100.0
2025-01-01 01:00:00   100.0   100.0
2025-01-01 02:00:00   100.0   100.0
2025-01-01 03:00:00   100.0   100.0
2025-01-01 04:00:00   100.0   100.0
...                     ...     ...
2025-12-31 19:00:00   100.0   100.0
2025-12-31 20:00:00   100.0   100.0
2025-12-31 21:00:00   100.0   100.0
2025-12-31 22:00:00   100.0   100.0
2025-12-31 23:00:00   100.0   100.0

[8760 rows x 2 columns]

In [13]:
n.add('Load',
      'Load C',
      bus = 'Location',
      p_set = 100,
      carrier = 'gas')

In [14]:
n.add('Generator',
      'Generator C',
      bus = 'Location', 
      p_nom = 500, 
      marginal_cost = 1,
      
      )

In [15]:
n.optimize()

C:\Users\PriyeshGosai\AppData\Local\Temp\ipykernel_33848\1261279110.py:1: FutureWarning: The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.
  n.optimize()
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 6/6 [00:00<00:00, 118.54it/s]
Writing continuous variables.: 100%|██████████| 2/2 [00:00<00:00, 443.91it/s]
INFO:linopy.io: Writing time: 0.07s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 17521 primals, 43801 duals
Objective: 2.63e+06
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Generator-ext-p-lower, Generator-ext-p-upper were not assigned to the network.

('ok', 'optimal')

In [16]:
n.add('Bus','Location',carrier = 'AC')

WARNING:pypsa.network.io:The following buses are already defined and will be skipped (use overwrite=True to overwrite): Location

In [19]:
n.add('Generator',
      'Generator C',
      bus = 'Location', 
      p_nom = 500, 
      marginal_cost = 1     
      )

WARNING:pypsa.network.io:The following generators are already defined and will be skipped (use overwrite=True to overwrite): Generator C

5. Build the full optimisation model (variables, constraints, objective).

In [ ]:
n.optimize.create_model()

In [ ]:
n.model

6. Pass that model to the solver and gets the results.

In [ ]:
n.optimize.solve_model()

We can also run both steps in sequence.

Therefore: 

```

n.optimize()

```

is the same as:


```

n.create_model()

n.solve_model()

```

7. Observe the results using the methods from pandas. 

* `plot()`
* `describe()`
* `sum()`

Since we are using the new api, we need to call is as follows:

`n.generators.dynamic.p.plot()`

In [ ]:
n.objective_constant

In [ ]:
n.buses.dynamic.marginal_price.sum()

In [ ]:
n.export_to_excel('lesson-2-solved.xlsx')